version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/FlaskAPI
  - source: requirements.txt
    destination: /home/ec2-user/FlaskAPI
permissions:
  - object: /home/ec2-user/FlaskAPI/APP/application.py
    owner: root
    mode: 775
    type:
      - file
hooks:
  ApplicationStop:
    - location: deploy/app_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/change_permissions.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: deploy/app_start.sh
      timeout: 60
      runas: root